### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by smlombardi** [chuyik/bower-existed-scanner#1]
Trying in OSX, followed instructions.

```
staryu:test stevelombardi$ cd '/Users/stevelombardi/github/test'
staryu:test stevelombardi$ node . ./app/bower_components

module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/stevelombardi/github/test'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

```

**Comment by mycaravam** [comment]
Anyone who finds this: use ``yarn add bower-existed-scanner``, then cd into ``node_modules/bower-existed-scanner``and run from there ``node . /your-dir/to/bower_components``.
